# Generated by Django 3.2.22 on 2023-10-18 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoriosMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('talla', models.CharField(choices=[('XS', 'xsmall'), ('SS', 'Small'), ('MM', 'Medium'), ('LL', 'Long'), ('XL', 'Xlong')], max_length=2)),
                ('stock', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Concesionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.TextField()),
                ('telefono', models.IntegerField(blank=True, unique=True)),
                ('fecha_apertura', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('ubicacion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(choices=[('KA', 'Kawasaki'), ('YA', 'Yamaha'), ('DU', 'Ducati'), ('HO', 'Honda'), ('BM', 'BMW'), ('TR', 'Triumph'), ('SZ', 'Suzuki'), ('KT', 'KTM')], max_length=2)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(blank=True, max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(blank=True, max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('preferencias', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VentaMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_compra', models.CharField(max_length=50)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.moto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='VentaConcesionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.CharField(max_length=50)),
                ('concesionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.concesionario')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.moto')),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(blank=True, unique=True)),
                ('concesionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moto.concesionario')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='moto',
            name='usuario',
            field=models.ManyToManyField(through='moto.VentaMoto', to='moto.Usuario'),
        ),
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.ManyToManyField(through='moto.ReservaEvento', to='moto.Usuario'),
        ),
        migrations.CreateModel(
            name='DatosTecnicosMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_serie', models.IntegerField(blank=True, unique=True)),
                ('cilindrada', models.IntegerField()),
                ('potencia', models.IntegerField()),
                ('velocidad_maxima', models.IntegerField()),
                ('tipo_motor', models.CharField(max_length=50)),
                ('consumo', models.FloatField()),
                ('sistema_frenado', models.CharField(max_length=50)),
                ('moto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moto.moto')),
            ],
        ),
        migrations.AddField(
            model_name='concesionario',
            name='moto',
            field=models.ManyToManyField(through='moto.VentaConcesionario', to='moto.Moto'),
        ),
        migrations.AddField(
            model_name='concesionario',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.trabajador'),
        ),
        migrations.CreateModel(
            name='CompraMasReciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('fecha_compra', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moto.usuario')),
            ],
        ),
    ]
