# Generated by Django 3.2.23 on 2023-11-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_evento', to='moto.evento'),
        ),
        migrations.AlterField(
            model_name='reservaevento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_usuario', to='moto.usuario'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajador_taller', to='moto.taller'),
        ),
        migrations.AlterField(
            model_name='ventaconcesionario',
            name='concesionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventaconc_concesionario', to='moto.concesionario'),
        ),
        migrations.AlterField(
            model_name='ventaconcesionario',
            name='moto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventaconc_moto', to='moto.moto'),
        ),
        migrations.AlterField(
            model_name='ventamoto',
            name='moto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventamoto_moto', to='moto.moto'),
        ),
        migrations.AlterField(
            model_name='ventamoto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventamoto_usuario', to='moto.usuario'),
        ),
    ]
