# Generated by Django 4.2.9 on 2024-02-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='imagen',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
