# Generated by Django 4.2.8 on 2023-12-17 01:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariologin',
            name='rol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'trabajador'), (2, 'cliente')], default=1),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.cliente')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.moto')),
            ],
        ),
    ]
