# Generated by Django 3.2.23 on 2023-11-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0002_auto_20231107_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaevento_evento', to='moto.evento'),
        ),
        migrations.AlterField(
            model_name='reservaevento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaevento_usuario', to='moto.usuario'),
        ),
    ]
