# Generated by Django 3.2.22 on 2023-11-05 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0002_alter_evento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concesionario',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajador_concesionario', to='moto.trabajador'),
        ),
    ]
