# Generated by Django 3.2.23 on 2023-11-08 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0003_auto_20231107_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='usuario',
            field=models.ManyToManyField(related_name='moto_vendida', through='moto.VentaMoto', to='moto.Usuario'),
        ),
        migrations.CreateModel(
            name='ValoracionMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(default=None)),
                ('comentario', models.TextField()),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoracion_moto', to='moto.moto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoracion_usuario', to='moto.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cuenta', models.CharField(blank=True, max_length=20, unique=True)),
                ('banco', models.CharField(choices=[('CA', 'Caixa'), ('BB', 'BBVA'), ('UC', 'UNICAJA'), ('IN', 'ING')], max_length=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_usuario', to='moto.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='moto',
            name='comentador',
            field=models.ManyToManyField(related_name='moto_comentada', through='moto.ValoracionMoto', to='moto.Usuario'),
        ),
    ]
