# Generated by Django 3.2.23 on 2023-11-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0004_auto_20231108_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionmoto',
            name='puntuacion',
            field=models.IntegerField(),
        ),
    ]
