# Generated by Django 4.2.9 on 2024-03-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0004_moto_caballos_moto_consumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotosReservada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nMotos', models.IntegerField(default=0)),
            ],
        ),
    ]
