# Generated by Django 4.2.10 on 2024-03-09 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0005_motosreservada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motosreservada',
            name='nMotos',
        ),
        migrations.AddField(
            model_name='motosreservada',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='motosreservada',
            name='moto',
            field=models.ManyToManyField(to='moto.moto'),
        ),
        migrations.AddField(
            model_name='motosreservada',
            name='usuario',
            field=models.ManyToManyField(to='moto.usuario'),
        ),
    ]
