# Generated by Django 3.2.23 on 2023-11-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0005_alter_valoracionmoto_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionmoto',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
    ]
