# Generated by Django 3.2.23 on 2023-11-08 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0006_alter_valoracionmoto_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracionmoto',
            name='fecha_votacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
