# Generated by Django 4.2.10 on 2024-02-09 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0007_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
