# Generated by Django 3.2.23 on 2023-12-11 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0007_valoracionmoto_fecha_votacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='date_deleted',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='evento',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='evento',
            name='model_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
